// =====================================================================
// Comida di Buteco 2026 — Montes Claros / MG
// Pratos participantes (20 botecos)
// Campos: id, boteco, prato, descricao, endereco, mapsUrl, lat, lng, foto
// =====================================================================

window.CDB_DISHES = [
  { id: 'balanca-vento', boteco: 'Balança Vento', prato: 'Sertãozinho', descricao: 'Bolinhos de carne de sol (cozida e desfiada) com queijo, mandioca e couve, temperados com especiarias defumadas, acompanhados de molho especial da casa.', endereco: 'Av. Castelar Prates, 382 — Major Prates', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Av.+Castelar+Prates%2C+382+%7C+Major+Prates%2C+Montes+Claros+-+MG', lat: -16.7517998, lng: -43.8770576, foto: 'images/balanca-vento.jpg' },
  { id: 'bar-do-kal', boteco: 'Bar do Kal', prato: 'Ela só Quer Verdura', descricao: 'Sanduíche que une os sabores do pernil suíno, do queijo e da nossa salada de cenoura e repolho. Acompanha molho do chef.', endereco: 'R. Antônio Martins, 50 — Santos Reis', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=R.+Ant%C3%B4nio+Martins%2C+50+%7C+Santos+Reis%2C+Montes+Claros+-+MG', lat: -16.7012758, lng: -43.8705204, foto: 'images/bar-do-kal.jpg' },
  { id: 'bar-do-soro', boteco: 'Bar do Soró', prato: 'Surpresinha do Soró', descricao: 'Rocambole de carne moída recheado, acompanhado de purê de batata e farofa de couve.', endereco: 'Rua Padre Eustáquio, 135 — São José', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Rua+Padre+Eust%C3%A1quio%2C+135+%7C+S%C3%A3o+Jos%C3%A9%2C+Montes+Claros%2C+MG', lat: -16.7212616, lng: -43.8559860, foto: 'images/bar-do-soro.jpg' },
  { id: 'botequim', boteco: 'Botequim', prato: 'La Casa de Boteco', descricao: 'Releitura da bruschetta italiana: pão amanteigado esfregado no alho com cream cheese e crispy de bacon, com mix agridoce de rúcula, tomate-cereja, cebola caramelizada e manjericão.', endereco: 'Av. Doutor Sidney Chaves, 895 — Edgar Pereira', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Av.+Doutor+Sidney+Chaves%2C+895+%7C+Edgar+Pereira%2C+Montes+Claros+-+MG', lat: -16.7107935, lng: -43.8604164, foto: 'images/botequim.jpg' },
  { id: 'cantina-da-paty', boteco: 'Cantina da Paty', prato: 'Mineirinha Turbinada', descricao: 'Dobradinha com pé de porco, calabresa e couve. Acompanha farofa de alho e cebola.', endereco: 'Rua J, 480 — Acácias', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Rua+J%2C+480+%7C+Ac%C3%A1cias%2C+Montes+Claros+-+MG', lat: -16.7246670, lng: -43.8192583, foto: 'images/cantina-da-paty.jpg' },
  { id: 'carrancas-grill', boteco: 'Carrancas Grill', prato: 'Pronobis e Proces', descricao: 'Rolinho de costela suína com ora-pro-nóbis, castanha de pequi e molho de umbu.', endereco: 'BR-365, 267 — Major Prates', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=BR-365%2C+267+%7C+Major+Prates%2C+Montes+Claros+-+MG', lat: -16.7614373, lng: -43.8842269, foto: 'images/carrancas-grill.jpg' },
  { id: 'diferencial-bar', boteco: 'Diferencial Bar', prato: 'Costelinha Diferenciada', descricao: 'Costelinha suína derretendo ao molho barbecue da casa e farofinha de alho-poró.', endereco: 'Av. Pedro Mendonça, 93 — Santos Reis', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Av.+Pedro+Mendon%C3%A7a%2C+93+%7C+Santos+Reis%2C+Montes+Claros+-+MG', lat: -16.7033673, lng: -43.8706375, foto: 'images/diferencial-bar.jpg' },
  { id: 'divinos-bar', boteco: "Divino's Bar", prato: 'Repolê Butecado', descricao: 'Canudos de repolho recheados com carne moída e bacon, finalizados com molho de tomate. Acompanha couve-flor gratinada ao molho branco e farofa de banana-da-terra com espinafre.', endereco: 'R. Luís Ruas, 62 — Santos Reis', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=R.+Lu%C3%ADs+Ruas%2C+62+%7C+Santos+Reis%2C+Montes+Claros+-+MG', lat: -16.7006913, lng: -43.8703029, foto: 'images/divinos-bar.jpg' },
  { id: 'dogmania', boteco: 'DogMania', prato: 'Sem Refrear', descricao: 'Mandioca derretida na manteiga de garrafa, coberta com carne serenada cozida e desfiada com toque de catupiry e queijo. Acompanha farofinha de bacon com couve e molhos de pimenta e queijo.', endereco: 'Alameda Beija-Flor, 390 — Jardim Primavera', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Alameda+Beija-Flor%2C+390+%7C+Jardim+Primavera%2C+Montes+Claros+-+MG', lat: -16.6952160, lng: -43.8104047, foto: 'images/dogmania.jpg' },
  { id: 'gordos-bar', boteco: "Gordo's Bar", prato: 'Trem Bão de Mais', descricao: 'Bolinhos de alho-poró com recheio de carne de sol e muçarela ao molho Vixe Maria.', endereco: 'Rua Raul Corrêa, 226 — Funcionários', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Rua+Raul+Corr%C3%AAa%2C+226+%7C+Funcion%C3%A1rios%2C+Montes+Claros+-+MG', lat: -16.7384938, lng: -43.8776553, foto: 'images/gordos-bar.jpg' },
  { id: 'imperial-bar', boteco: 'Imperial Bar', prato: 'Torresmo Imperador', descricao: 'Torresmo de barriga e mandioca derretida com alface picada.', endereco: 'Rua Campo Belo, 1455', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Rua+Campo+Belo%2C+1455+%7C+Montes+Claros+-+MG', lat: -16.7397186, lng: -43.8552827, foto: 'images/imperial-bar.jpg' },
  { id: 'kentura-2', boteco: 'Kentura 2', prato: 'Ora, Porco-Nóbis!', descricao: 'Pastel de carne de porco com ora-pro-nóbis crocante caramelizado ao molho de tamarindo.', endereco: 'Rua Santa Maria, 662 — Todos os Santos', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Rua+Santa+Maria%2C+662+%7C+Todos+os+Santos%2C+Montes+Claros+-+MG', lat: -16.7192714, lng: -43.8708557, foto: 'images/kentura-2.jpg' },
  { id: 'liu-casa-bar', boteco: 'Liu Casa Bar', prato: 'Dobradinha com toque de alho-poró', descricao: 'Dobradinha tradicional, preparada com caldo aromático e textura macia.', endereco: 'R. Espírito Santo, 246 — Esplanada', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=R.+Esp%C3%ADrito+Santo%2C+246+%7C+Esplanada%2C+Montes+Claros+-+MG', lat: -16.7157962, lng: -43.8408428, foto: 'images/liu-casa-bar.jpg' },
  { id: 'moc-sabor', boteco: 'Moc Sabor', prato: 'Poróbuteco', descricao: 'Polpetone de picanha suína, empanado no Panko, recheado com muçarela e molho de alho-poró. Acompanha vinagrete e chips de banana.', endereco: 'Av. São Judas, 1458 — São Judas Tadeu I', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Av.+S%C3%A3o+Judas%2C+1458+%7C+S%C3%A3o+Judas+Tadeu+I%2C+Montes+Claros+-+MG', lat: -16.7496427, lng: -43.8542817, foto: 'images/moc-sabor.jpg' },
  { id: 'nobres-bar', boteco: "Nobre's Bar", prato: 'Costelinha suína com farofa de folhas', descricao: 'Costelinha suína frita, servida com molho barbecue ao lado de farofa com folhas de couve, repolho, bacon e cenoura ralada.', endereco: 'Avenida A, 981 — Jardim Primavera', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Avenida+A%2C+981+%7C+Jardim+Primavera%2C+Montes+Claros+-+MG', lat: -16.6969805, lng: -43.8113603, foto: 'images/nobres-bar.jpg' },
  { id: 'pe-de-cana', boteco: 'Pé de Cana', prato: 'Descubra-me se for capaz', descricao: 'Escondidinho de carne com purê de abóbora e couve, finalizado com crispy de bacon.', endereco: 'Av. Ampére, 462 — Lourdes', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Av.+Amp%C3%A9re%2C+462+%7C+Lourdes%2C+Montes+Claros+-+MG', lat: -16.7244266, lng: -43.8506895, foto: 'images/pe-de-cana.jpg' },
  { id: 'petisco-de-ouro', boteco: 'Petisco de Ouro', prato: 'Panelada de Ouro', descricao: 'Galinhada com alho-poró e milho, acompanhada de farofa de couve com óleo de pequi e bacon.', endereco: 'R. Júlio Takaki, 221 — São Judas Tadeu', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=R.+J%C3%BAlio+Takaki%2C+221+%7C+S%C3%A3o+Judas+Tadeu%2C+Montes+Claros+-+MG', lat: -16.7488977, lng: -43.8612485, foto: 'images/petisco-de-ouro.jpg' },
  { id: 'sao-bento', boteco: 'São Bento Espetaria', prato: 'Polpetone ao molho pomodoro', descricao: 'Bolinho de carne bovina moída recheado com espinafre e muçarela, empanado, servido com molho pomodoro.', endereco: 'R. Barão do Rio Branco, 253 — Centro', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=R.+Bar%C3%A3o+do+Rio+Branco%2C+253+%7C+Centro%2C+Montes+Claros+-+MG', lat: -16.7268106, lng: -43.8678665, foto: 'images/sao-bento.jpg' },
  { id: 'uai-fai-bar-moc', boteco: 'Uai Fai Bar MOC', prato: 'Bem-casado do UAI', descricao: 'Duo de filé de peixe e filé de peito de frango grelhado ao molho de verduras, salsão e vinho branco.', endereco: 'Av. Nossa Senhora de Fátima, 1232 — Maracanã', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Av.+Nossa+Senhora+de+F%C3%A1tima%2C+1232+%7C+Maracan%C3%A3%2C+Montes+Claros+-+MG', lat: -16.7569037, lng: -43.8696329, foto: 'images/uai-fai-bar-moc.jpg' },
  { id: 'villa-espetaria', boteco: 'Villa Espetaria', prato: 'Panqueca verde cremosa', descricao: 'Panqueca com massa de brócolis, recheada com carne bovina desfiada cremosa, cream cheese e molho de tomate caseiro.', endereco: 'R. Genésio Tolentino, 15 — Cidade Nova', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=R.+Gen%C3%A9sio+Tolentino%2C+15+%7C+Cidade+Nova%2C+Montes+Claros+-+MG', lat: -16.7387482, lng: -43.8660289, foto: 'images/villa-espetaria.jpg' },
];
